export type ThaiRegion = "north" | "northeast" | "central" | "east" | "west" | "south";
export type HospitalStatus = "online" | "warning" | "critical" | "offline";

export interface NetworkHospital {
  id: string;
  nameTh: string;
  nameEn: string;
  shortCode: string;
  province: string;
  region: ThaiRegion;
  capacity: number;
  status: HospitalStatus;
  beds: number;
  connected: boolean;
  inflow: number;
  compliance: number;
  alarms: number;
  mapX: number;
  mapY: number;
}

export interface RegionInfo {
  nameTh: string;
  nameEn: string;
  fill: string;
  fillHover: string;
  fillSelected: string;
  stroke: string;
  accent: string;
  // Light-mode variants (used when html lacks .dark class)
  fillLight: string;
  fillHoverLight: string;
  fillSelectedLight: string;
  accentLight: string;
}

export const REGION_INFO: Record<ThaiRegion, RegionInfo> = {
  north: {
    nameTh: "ภาคเหนือ",
    nameEn: "Northern",
    fill: "#0e3148",
    fillHover: "#164968",
    fillSelected: "#1a6090",
    stroke: "#2d8abf",
    accent: "#67c8ff",
    fillLight: "#dbeefe",
    fillHoverLight: "#bfe0fc",
    fillSelectedLight: "#9fcff8",
    accentLight: "#0c5a87",
  },
  northeast: {
    nameTh: "ภาคอีสาน",
    nameEn: "Northeastern",
    fill: "#3b2800",
    fillHover: "#573c00",
    fillSelected: "#7a5500",
    stroke: "#c48a00",
    accent: "#fbbf24",
    fillLight: "#fef3c7",
    fillHoverLight: "#fde68a",
    fillSelectedLight: "#fcd34d",
    accentLight: "#92400e",
  },
  central: {
    nameTh: "ภาคกลาง",
    nameEn: "Central",
    fill: "#0a2d4a",
    fillHover: "#123f68",
    fillSelected: "#1a5288",
    stroke: "#2563eb",
    accent: "#60a5fa",
    fillLight: "#dbeafe",
    fillHoverLight: "#bfdbfe",
    fillSelectedLight: "#93c5fd",
    accentLight: "#1d4ed8",
  },
  east: {
    nameTh: "ภาคตะวันออก",
    nameEn: "Eastern",
    fill: "#2c1552",
    fillHover: "#3e1f72",
    fillSelected: "#502994",
    stroke: "#7c3aed",
    accent: "#c084fc",
    fillLight: "#ede9fe",
    fillHoverLight: "#ddd6fe",
    fillSelectedLight: "#c4b5fd",
    accentLight: "#6d28d9",
  },
  west: {
    nameTh: "ภาคตะวันตก",
    nameEn: "Western",
    fill: "#0a2e1e",
    fillHover: "#124430",
    fillSelected: "#1a5c42",
    stroke: "#059669",
    accent: "#34d399",
    fillLight: "#d1fae5",
    fillHoverLight: "#a7f3d0",
    fillSelectedLight: "#6ee7b7",
    accentLight: "#047857",
  },
  south: {
    nameTh: "ภาคใต้",
    nameEn: "Southern",
    fill: "#3d1506",
    fillHover: "#5a1f09",
    fillSelected: "#7a2c0d",
    stroke: "#c2410c",
    accent: "#fb923c",
    fillLight: "#ffedd5",
    fillHoverLight: "#fed7aa",
    fillSelectedLight: "#fdba74",
    accentLight: "#9a3412",
  },
};

export const HOSPITALS: NetworkHospital[] = [
  // ภาคเหนือ
  {
    id: "h-cm",
    nameTh: "โรงพยาบาลมหาราชนครเชียงใหม่",
    nameEn: "Maharaj Nakorn Chiang Mai Hospital",
    shortCode: "MNH-CM",
    province: "เชียงใหม่",
    region: "north",
    capacity: 2800,
    status: "online",
    beds: 1400,
    connected: false,
    inflow: 94,
    compliance: 98,
    alarms: 0,
    mapX: 45,
    mapY: 52,
  },
  {
    id: "h-lpg",
    nameTh: "โรงพยาบาลลำปาง",
    nameEn: "Lampang General Hospital",
    shortCode: "LPG",
    province: "ลำปาง",
    region: "north",
    capacity: 1200,
    status: "online",
    beds: 900,
    connected: false,
    inflow: 41,
    compliance: 96,
    alarms: 1,
    mapX: 68,
    mapY: 72,
  },
  {
    id: "h-cr",
    nameTh: "โรงพยาบาลเชียงรายประชานุเคราะห์",
    nameEn: "Chiang Rai Prachanukroh Hospital",
    shortCode: "CRP",
    province: "เชียงราย",
    region: "north",
    capacity: 900,
    status: "warning",
    beds: 800,
    connected: false,
    inflow: 30,
    compliance: 89,
    alarms: 3,
    mapX: 90,
    mapY: 28,
  },
  {
    id: "h-nan",
    nameTh: "โรงพยาบาลน่าน",
    nameEn: "Nan General Hospital",
    shortCode: "NAN",
    province: "น่าน",
    region: "north",
    capacity: 600,
    status: "online",
    beds: 500,
    connected: false,
    inflow: 20,
    compliance: 97,
    alarms: 0,
    mapX: 108,
    mapY: 52,
  },

  // ภาคอีสาน — grid rect: x:127-195, y:5-225
  {
    id: "h-udon",
    nameTh: "โรงพยาบาลอุดรธานี",
    nameEn: "Udon Thani Hospital",
    shortCode: "UDH",
    province: "อุดรธานี",
    region: "northeast",
    capacity: 1800,
    status: "online",
    beds: 1000,
    connected: false,
    inflow: 61,
    compliance: 94,
    alarms: 0,
    mapX: 148,
    mapY: 55,
  },
  {
    id: "h-kk",
    nameTh: "โรงพยาบาลขอนแก่น",
    nameEn: "Khon Kaen Hospital",
    shortCode: "KKH",
    province: "ขอนแก่น",
    region: "northeast",
    capacity: 2200,
    status: "online",
    beds: 1200,
    connected: false,
    inflow: 74,
    compliance: 95,
    alarms: 2,
    mapX: 155,
    mapY: 95,
  },
  {
    id: "h-krt",
    nameTh: "โรงพยาบาลมหาราชนครราชสีมา",
    nameEn: "Maharat Nakhon Ratchasima Hospital",
    shortCode: "KRT",
    province: "นครราชสีมา",
    region: "northeast",
    capacity: 3000,
    status: "warning",
    beds: 1600,
    connected: false,
    inflow: 102,
    compliance: 88,
    alarms: 5,
    mapX: 145,
    mapY: 148,
  },
  {
    id: "h-ubn",
    nameTh: "โรงพยาบาลสรรพสิทธิประสงค์",
    nameEn: "Sunpasitthiprasong Hospital",
    shortCode: "SPH",
    province: "อุบลราชธานี",
    region: "northeast",
    capacity: 1500,
    status: "critical",
    beds: 900,
    connected: false,
    inflow: 50,
    compliance: 72,
    alarms: 8,
    mapX: 175,
    mapY: 125,
  },

  // ภาคกลาง — grid rect: x:50-122, y:110-225
  {
    id: "h-siriraj",
    nameTh: "โรงพยาบาลศิริราช",
    nameEn: "Siriraj Hospital",
    shortCode: "SRJ",
    province: "กรุงเทพมหานคร",
    region: "central",
    capacity: 6300,
    status: "warning",
    beds: 2300,
    connected: true,
    inflow: 292,
    compliance: 92,
    alarms: 4,
    mapX: 72,
    mapY: 168,
  },
  {
    id: "h-rama",
    nameTh: "โรงพยาบาลรามาธิบดี",
    nameEn: "Ramathibodi Hospital",
    shortCode: "RMH",
    province: "กรุงเทพมหานคร",
    region: "central",
    capacity: 4500,
    status: "online",
    beds: 1900,
    connected: false,
    inflow: 155,
    compliance: 97,
    alarms: 1,
    mapX: 85,
    mapY: 180,
  },
  {
    id: "h-suphanburi",
    nameTh: "โรงพยาบาลเจ้าพระยายมราช",
    nameEn: "Chao Phraya Yommarat Hospital",
    shortCode: "CPY",
    province: "สุพรรณบุรี",
    region: "central",
    capacity: 900,
    status: "online",
    beds: 600,
    connected: false,
    inflow: 30,
    compliance: 99,
    alarms: 0,
    mapX: 60,
    mapY: 135,
  },

  // ภาคตะวันออก — grid rect: x:127-195, y:230-295
  {
    id: "h-chonburi",
    nameTh: "โรงพยาบาลชลบุรี",
    nameEn: "Chonburi Hospital",
    shortCode: "CBH",
    province: "ชลบุรี",
    region: "east",
    capacity: 1600,
    status: "online",
    beds: 900,
    connected: false,
    inflow: 54,
    compliance: 96,
    alarms: 0,
    mapX: 145,
    mapY: 248,
  },
  {
    id: "h-rayong",
    nameTh: "โรงพยาบาลระยอง",
    nameEn: "Rayong Hospital",
    shortCode: "RYH",
    province: "ระยอง",
    region: "east",
    capacity: 1000,
    status: "online",
    beds: 600,
    connected: false,
    inflow: 34,
    compliance: 98,
    alarms: 0,
    mapX: 162,
    mapY: 260,
  },
  {
    id: "h-trat",
    nameTh: "โรงพยาบาลตราด",
    nameEn: "Trat Hospital",
    shortCode: "TRD",
    province: "ตราด",
    region: "east",
    capacity: 500,
    status: "warning",
    beds: 400,
    connected: false,
    inflow: 17,
    compliance: 84,
    alarms: 2,
    mapX: 178,
    mapY: 274,
  },

  // ภาคตะวันตก — grid rect: x:5-45, y:110-225
  {
    id: "h-kan",
    nameTh: "โรงพยาบาลพหลพลพยุหเสนา",
    nameEn: "Phaholpolpayuhasena Hospital",
    shortCode: "KBH",
    province: "กาญจนบุรี",
    region: "west",
    capacity: 1000,
    status: "online",
    beds: 650,
    connected: false,
    inflow: 34,
    compliance: 97,
    alarms: 0,
    mapX: 18,
    mapY: 148,
  },
  {
    id: "h-phet",
    nameTh: "โรงพยาบาลพระจอมเกล้าเพชรบุรี",
    nameEn: "Phrachomklao Phetchaburi Hospital",
    shortCode: "PCK",
    province: "เพชรบุรี",
    region: "west",
    capacity: 800,
    status: "online",
    beds: 520,
    connected: false,
    inflow: 27,
    compliance: 96,
    alarms: 1,
    mapX: 18,
    mapY: 192,
  },

  // ภาคใต้ — grid rect: x:50-122, y:230-432
  {
    id: "h-surat",
    nameTh: "โรงพยาบาลสุราษฎร์ธานี",
    nameEn: "Suratthani Hospital",
    shortCode: "STH",
    province: "สุราษฎร์ธานี",
    region: "south",
    capacity: 1500,
    status: "warning",
    beds: 800,
    connected: false,
    inflow: 50,
    compliance: 88,
    alarms: 3,
    mapX: 72,
    mapY: 265,
  },
  {
    id: "h-nst",
    nameTh: "โรงพยาบาลมหาราชนครศรีธรรมราช",
    nameEn: "Maharaj Nakhon Si Thammarat Hospital",
    shortCode: "NST",
    province: "นครศรีธรรมราช",
    region: "south",
    capacity: 1800,
    status: "online",
    beds: 1000,
    connected: false,
    inflow: 62,
    compliance: 96,
    alarms: 1,
    mapX: 90,
    mapY: 308,
  },
  {
    id: "h-phuket",
    nameTh: "โรงพยาบาลวชิระภูเก็ต",
    nameEn: "Vachira Phuket Hospital",
    shortCode: "VPH",
    province: "ภูเก็ต",
    region: "south",
    capacity: 1200,
    status: "online",
    beds: 700,
    connected: false,
    inflow: 41,
    compliance: 99,
    alarms: 0,
    mapX: 58,
    mapY: 352,
  },
  {
    id: "h-hatyai",
    nameTh: "โรงพยาบาลหาดใหญ่",
    nameEn: "Hat Yai Hospital",
    shortCode: "HYH",
    province: "สงขลา",
    region: "south",
    capacity: 2500,
    status: "online",
    beds: 1200,
    connected: false,
    inflow: 85,
    compliance: 95,
    alarms: 2,
    mapX: 78,
    mapY: 390,
  },
  {
    id: "h-yala",
    nameTh: "โรงพยาบาลยะลา",
    nameEn: "Yala Hospital",
    shortCode: "YLH",
    province: "ยะลา",
    region: "south",
    capacity: 700,
    status: "offline",
    beds: 450,
    connected: false,
    inflow: 0,
    compliance: 0,
    alarms: 0,
    mapX: 65,
    mapY: 420,
  },
];

export const STATUS_CONFIG: Record<
  HospitalStatus,
  { label: string; color: string; dot: string; badge: string }
> = {
  online: {
    label: "ออนไลน์",
    color: "#22c55e",
    dot: "bg-green-500",
    badge: "bg-green-500/15 text-green-400 border-green-500/40",
  },
  warning: {
    label: "เฝ้าระวัง",
    color: "#f59e0b",
    dot: "bg-amber-500",
    badge: "bg-amber-500/15 text-amber-400 border-amber-500/40",
  },
  critical: {
    label: "วิกฤต",
    color: "#ef4444",
    dot: "bg-red-500",
    badge: "bg-red-500/15 text-red-400 border-red-500/40",
  },
  offline: {
    label: "ออฟไลน์",
    color: "#6b7280",
    dot: "bg-slate-500",
    badge: "bg-slate-700 text-slate-400 border-slate-600",
  },
};
